### ISSUE TITLE
Converting error

### ISSUE THREAD

**Issue by MrRefactoring** [manifoldco/swagger-to-ts#13]
What can we do with this error?

```bash
λ npx @manifoldco/swagger-to-ts swagger.json --namespace OpenAPI --output schema.ts
npx: installed 63 in 9.204s
Property or signature expected. (330:1)
  328 | export interface UserList {
  329 | // The index of the last item returned on the page.
> 330 | end-index?: number;
      | ^
  331 | // The list of items.
  332 | items?: User[];
  333 | // The maximum number of results that could be on the page.
```

**Comment by dangodev** [comment]
Which of the following would you prefer?

```ts
export interface UserList {
  // The index of the last item returned on the page.
  'end-index'?: number;
```

```ts
export interface UserList {
  // The index of the last item returned on the page.
  endIndex: number;
```

**Comment by dangodev** [comment]
The latter can be fixed by specifying `--camelcase`, but you’re right the former would break. Let me see if there‘s an easy way to handle the former.

**Comment by MrRefactoring** [comment]
I would prefer the second option, but I was surprised when I could not collect the typescript from the swagger.  Thanks for correcting this error.  If you wish, I will test your PR tomorrow

**Comment by dangodev** [comment]
@MrRefactoring whenever you get a chance, try `npx @swagger-to-ts@beta` and let me know if that fixes the issue. But `--camelCase` should be working now.

Also note that I just published a new minor version with a breaking change. In your example, try this instead (you can specify anything for `wrapper`):

```
npx @manifoldco/swagger-to-ts swagger.json --wrapper 'declare namespace OpenAPI' --output schema.d.ts
```

**Comment by MrRefactoring** [comment]
Cool. Now everything works!
