### ISSUE TITLE
Cannot read property 'items' of undefined

### ISSUE THREAD

**Issue by elie222** [manifoldco/swagger-to-ts#133]
Release 1.6.1 introduced a bug. When running the generator we get:

```
Error: TypeError: Cannot read property 'items' of undefined
```

Related code:

```js
    if ($ref) {
      const [refName, refProperties] = getRef($ref);
      const convertedRefName = spacesToUnderscores(refName);

      if (refProperties.items && refProperties.items.$ref) {
        return getType(refProperties, refName);
      }
```

Works fine for us in 1.6.0 and 1.5.x.

**Comment by dangodev** [comment]
Hey @elie222 thanks for reporting this. Are you able to provide an example of your schema that breaks this? 

Also you may be interested in an [improved 2.0 version of this library](https://github.com/manifoldco/swagger-to-ts/pull/178) which is currently in `alpha`, that also may fix the problem.

**Comment by elie222** [comment]
Thanks. We found a workaround for the issue at the time. It’s a project I finished working on in any case but I’ll let the others know that v2 could be worth checking out. Thanks!

**Comment by dangodev** [comment]
Glad you got it sorted. Also sorry for the inconvenience!

**Comment by dangodev** [comment]
`@manifoldco/swagger-to-ts@2.0.0` was just released on npm, which is a library rewrite that adds OpenAPI 3.0 support as well as fixes a myriad of issues. I believe this will fix your issue, but please let me know if this pops up again.
