### ISSUE TITLE
Create types from URL

### ISSUE THREAD

**Issue by psmyrdek** [manifoldco/swagger-to-ts#187]
As far as I see, this library doesn't support creating specs based on the remote resources yet. Reasoning would be that in microservices environment, there are many modules which expose spec on given URL, but not all of them publish it as a package to some internal package registries.

For example, one could imagine the following API:

```
npx @manifoldco/swagger-to-ts --url https://remote.com/specs.json --output schema.d.ts
```

Can I try introducing such a PR? How do we feel about such an improvement? How the ideal flow would look like?

**Comment by RinatGumarov** [comment]
It will be useful for me too. Also I shouldn't write it here, but I also want to enum type to be parsed properly

**Comment by dangodev** [comment]
@psmyrdek a PR for that would be greatly appreciated!

What about if we just skipped the `--url` flag altogether, and just accepted it as the main input?

```
npx @manifoldco/swagger-to-js https://remote.com/specs.json …
```

I think that’d keep the API simpler. And it’d save us from having to conditionally require that first param or not.

It’s not exactly outlined, but a goal of this project is to keep dependencies as few as possible for performance. So if we could get away with using Node’s core `http`/`https` modules for fetching that’d be ideal.

**Comment by dangodev** [comment]
> Also I shouldn't write it here, but I also want to enum type to be parsed properly.

You sure shouldn’t write a different issue in an unrelated ticket! 😛 Feel free to open another issue with a reproduction of your issue and the version you’re using please 🙇

**Comment by psmyrdek** [comment]
@dangodev Sounds good - will prepare a PR as quickly as I can.
