### ISSUE TITLE
Unknown option --output

### ISSUE THREAD

**Issue by henhal** [manifoldco/swagger-to-ts#221]
I installed the latest from npm and followed the examples, without success (it looks like this page is for the upcoming 2.0 release already?).

```
$ npx @manifoldco/swagger-to-ts spec.yml --output schema.ts
error: unknown option '--output'

$ npx @manifoldco/swagger-to-ts spec.yml
[INFO]: 下载 Swagger..., apiUrl: 
[ERROR]: 下载 Swagger 失败
Error: Expected a file path, URL, or object. Got undefined
```

**Comment by dangodev** [comment]
@henhal thanks for opening an issue. Yes—there is a `2.0` release coming soon that’s almost ready but not quite. Maybe it works better for you?

Just add `@next` to the end of the library name like so:

```bash
$ npx @manifoldco/swagger-to-ts@next …
```

**Comment by dangodev** [comment]
This is now in the `latest` version! We’ve rewritten the entire library for `@manifoldco/swagger-to-ts@2.0.0` which includes OpenAPI 3.0 support and fixes a number of issues. Hopefully this should fix your problem! Please file another issue if it doesn’t.

**Comment by henhal** [comment]
Cool! I missed the previous comment, will try this out! 👍

**Comment by henhal** [comment]
I now get this to work, however with some limitations that kind of break it for me, so I will place another issue for you to consider.
