### ISSUE TITLE
--prettier-config throws misleading error if custom config isn't JSON

### ISSUE THREAD

**Issue by ikornienko** [manifoldco/swagger-to-ts#222]
When I used `--prettier-config .prettierrc.js` I've got an an error `Prettier: couldn’t find '.prettierrc.js' in ...`. It turned out that the error is misleading, as the exception was about config not being a valid JSON.

In general, I see more and more people prefer `.eslintrc.js` and `prettierrc.js` over JSON, as JavaScript allows sharing configurations through import / export (and it's just nicer than JSON). Haven't found Prettier exposing any API for reading the config file, but it does [state in the docs](https://prettier.io/docs/en/configuration.html) it uses [cosmiconfig](https://github.com/davidtheclark/cosmiconfig). It would be great if `swagger-to-ts` also used `cosmiconfig` to read any Prettier config file.

**Comment by dangodev** [comment]
That’s a good idea! I think that’s a great add. I’d love a PR if you have time, but if not I’d be happy to add this.

**Comment by ikornienko** [comment]
Thanks, @dangodev! Unfortunately, I cannot commit to creating a PR in any short-term future. If you have capacity to do it, please go for it.

**Comment by dangodev** [comment]
No worries. I’ll see if I can get this in for the `2.0` launch. Thanks again for the issue!

**Comment by dangodev** [comment]
Just released a new `next` version to npm that uses Prettier’s [resolveConfig](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options) option instead to support all the configurations Prettier does. Give it a try:

```bash
npx @manifoldco/swagger-to-ts@next …
```

I added a test and confirmed that `.js` format is working, but I didn’t test out all the different Prettier configurations (hopefully Prettier handles that for us!). Please let me know if you still experience the issue.
