### ISSUE TITLE
TypeError: swaggerToTS is not a function

### ISSUE THREAD

**Issue by bsubba** [manifoldco/swagger-to-ts#241]
I am trying to use this library to generate typescript from swagger definition but I am getting the following error. What am I missing here?
`TypeError: swaggerToTS is not a function`

```
const swaggerToTS = require("@manifoldco/swagger-to-ts");

const input = JSON.parse(readFileSync("src/buildSwagger/swagger.json", "utf8")); 
const output = swaggerToTS(input);  
```

**Comment by drwpow** [comment]
Try `require("@manifoldco/swagger-to-ts").default`. The docs should be updated though you’re right. Sorry about that.
