### ISSUE TITLE
How to remove wrapper ?

### ISSUE THREAD

**Issue by Meyzz** [manifoldco/swagger-to-ts#259]
In 1.5 version i could add {wrapper: false}, now i cant ?
I want use interfaces by just it name - `UserRole` without strings and nested interfaces -`definitions['User']['role']`

**Comment by akellbl4** [comment]
You can find explanation in docs.
https://github.com/manifoldco/swagger-to-ts#no-wrappers

**Comment by IkeyBenz** [comment]
> You can find explanation in docs.

The docs seem to say that what @Meyzz was looking for can no longer be achieved... am I misunderstanding? I would also like to reference interfaces by name.

**Comment by drwpow** [comment]
Yes that’s correct—with 2.0 the option to remove wrappers was removed. It made the library overly-complicated to maintain when your schema can be transformed. It’s your schema! The types should match reality.

As referenced in the README, I’d recommend just creating shorthand types where needed to reduce typing.

**Comment by skh-** [comment]
@Meyzz if you're just looking for fewer keystrokes, here's what I came up with:

in a `.d.ts` file:

```ts
import { components } from 'your-module';

declare global {
  type Schemas = components['schemas'];
}
```

Usage: `const foo: Schemas['Foo'] = makeFoo();` in a different file without having to import anything.

**Comment by fgblomqvist** [comment]
It feels quite non-typescript'y to have to write even `Schemas['Foo']`. Feels like everything in `components['schemas']` should be directly importable/referenceable. If you have to use a nested structure for accessing paths/methods etc. and other more complicated/niche bits, that's fine.

> The types should match reality.

The types do match reality. Nesting them does not feel like it matches reality though. If I have a type `Foo` shouldn't I be able to just do `import { Foo } from './schema.ts';`?
@drwpow
