### ISSUE TITLE
swagger-to-ts considers components mandatory

### ISSUE THREAD

**Issue by henhal** [manifoldco/swagger-to-ts#262]
When running `swagger-to-ts` on a specification without `components`, it immediately fails.
However, `components` is an [optional part of the api schema](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml#L5) and I can think of at least two scenarios where it would not be present:

1. All schemas are inline in `paths`
2. All schemas are put in separate file(s) such as `schemas.yml`

My specifications are quite large and I tend to split them up into separate files as per 2). This means that operations reference schemas such as `{$ref: './schemas/foo.yml#/Foo'}`.
Neither of these two approaches seem to work with `swagger-to-ts` since it requires `components` to be present (and, I assume, also ignores any schemas outside of `components`)?

1. Would it be possible to invoke swagger-to-ts with a raw schema file, i.e., one that simply contains the schemas instead of requiring a full OpenAPI document?
2. Would it be possible to properly support OpenAPI documents without `components`? It should be possible to fetch all externally referenced schemas using standard json-ref-parser etc?

**Comment by hasparus** [comment]
I encountered the same problem with openapi schema generated from Django :c

**Comment by drwpow** [comment]
Just merged #236, so this will go out with the next release!
