### ISSUE TITLE
Doesn't work on non-standard ports

### ISSUE THREAD

**Issue by macroexp** [manifoldco/swagger-to-ts#267]
At least on macOS platform, running node v14.3.0, using a url such as http://192.168.7.245:8091/doc/swagger/swagger.yaml results in an error "Error: getaddrinfo ENOTFOUND 192.168.7.245:8091" - clearly, some code that is attempting to split the url up is not splitting the port off the host part before doing a lookup.

**Comment by selbekk** [comment]
Yeah same here. Created a PR to fix it :)

**Comment by drwpow** [comment]
This is fixed in #252. Will go out in the next release
