### ISSUE TITLE
Bug: integer enum type is converted into string enum type wrongly

### ISSUE THREAD

**Issue by FourF-src** [manifoldco/swagger-to-ts#278]
Hi, in my swagger.json file, I have this definition:
```json
        "jobStatus": {
          "type": "integer",
          "format": "int32",
          "description": "0: created, 1: uploading, 2: uploading failed, 3: ingesting, 4: ingestion failed, 5: successful",
          "enum": [
            0,
            1,
            2,
            3,
            4,
            5
          ]
        },
```
But after I processed it by swagger-to-ts, I got something like this:
```typescript
    jobStatus?: "0" | "1" | "2" | "3" | "4" | "5";
```
which is supposed to be
```typescript
    jobStatus?: 0 | 1 | 2 | 3 | 4 | 5;
```

Could you kindly help to fix this bug? 😊

**Comment by FourF-src** [comment]
#266

**Comment by drwpow** [comment]
#266 merged! It will go out in the next release.

**Comment by KumaCool** [comment]
Can the `enum` in Swagger be directly converted to the `enum type` of TS?
```
 // ts definition:
enum a {A, B, C}

 // openapi definition:
interface b {
  a: 'A' | 'B' | 'C'
}

a !== b.a
```
Because of the `number` returned by the service, the `string` I defined locally.
I need both. If you only use `string`, the type will not match
## Desired result
```
 // openapi definition:
enum a {A, B, C}
interface b {
  a: a
}
```
@drwpow

**Comment by drwpow** [comment]
> Can the enum in Swagger be directly converted to the enum type of TS?

Funny enough, the very first version did this! But after using it in a real application, I found it to be waay harder to use than a discriminated string union type. For example:

```ts
import { components } from './schema.ts';

const myObj: components["schema"]["MySchema"] = {
  enum: 'A' // ✅
}
```

this just works. If we went with a true TS enum, we’d have to do something like:

```ts
import { components } from './schema.ts';

const myObj: components["schema"]["MySchema"] = {
  enum: 'A' // ❌
  enum: components["schema"]["MySchema"]["enum"].A // ✅
}
```

When you’re working a lot with schemas, this becomes pretty frustrating quickly. It’s just a problem with the way OpenAPI maps to TypeScript: enums are great going from TypeScript -> TypeScript. But quickly become annoying trying to generate them in OpenAPI.

Hopefully that explains some of the reasoning.

**Comment by KumaCool** [comment]
How to establish a relationship with the enum defined by the service?
The service api requires parameters whose status is `number`
I need to display the `string` corresponding to the status in the local `<select valueEnum={status} />` and set status value.
Is there any solution?

**Comment by drwpow** [comment]
> I need to display the `string` corresponding to the status in the local `<select valueEnum={status} />` and set status value.

That crosses over into state, which is separate from TypeScript types. Since you have to store the value in memory, I’d recommend something [related to this SO answer](https://stackoverflow.com/questions/53685667/use-enum-in-angular-to-select-drop-menu-item/53686606), but using a discriminated union instead, e.g.:

```ts
import { components } from './schema.ts';

type MyEnumType = components["schema"]["MySchemaType"]["myEnumField"]; // 'one' | 'two' | 'three'

const selectOptions: Record<MyEnumType, string> = {
  one: 'Option One',
  two: 'Option Two',
  three: 'Option Three'
}

// …

`<select valueEnum={selectOptions} />`
```

This is all pseudo-code; I don’t know what framework you’re using, but hopefully this makes sense. Main point is that your OpenAPI schema is meant to **validate** your code, not compose it. You still have to compose the actual code that executes, which often involves managing some values yourselves (this library only generates types, not actual code).
