### ISSUE TITLE
--nowrapper CLI option does not work properly

### ISSUE THREAD

**Issue by MrCrunchwrap** [manifoldco/swagger-to-ts#43]
The cli `--nowrapper` option doesn't seem to work properly. I'm using it in my command and my types are still wrapped with `declare namespace OpenAPI2`

**Comment by dangodev** [comment]
At the time this issue was opened, the `--nowrapper` flag was in `master` but hadn’t been published to npm yet. I was able to test & deploy that feature today, so this should be working as intended.

Please feel free to re-open this issue if you experience any problems with `--nowrapper`.

**Comment by MrCrunchwrap** [comment]
Thanks!
