### ISSUE TITLE
Two-dimensional arrays not handled?

### ISSUE THREAD

**Issue by scvnathan** [manifoldco/swagger-to-ts#46]
Hi, it looks like two-dimensional arrays are not being handled, which I noticed in my own project but I've replicated the behavior here by modifying `example/input.yaml`:
```
  Provider:
    type: object
    properties:
      id: { $ref: '#/definitions/ID' }
      version: { type: integer, enum: [1] }
      type: { type: string, enum: ['provider'] }
      body: { $ref: '#/definitions/ProviderBody' }
      twoDimArray:
        type: array
        items:
          type: array
          items: { $ref: '#/definitions/ProviderBody' }
    additionalProperties: false
    required:
      - id
      - version
      - type
      - body
```

I would expect the generated type to be:
```
export interface Provider {
  id: string;
  version: 1;
  type: 'provider';
  body: ProviderBody;
  twoDimArray?: ProviderBody[][];
}
```
But it ends up generating this:
```
export interface Provider {
  id: string;
  version: 1;
  type: 'provider';
  body: ProviderBody;
  twoDimArray?: ProviderTwoDimArray[];
}
export interface ProviderTwoDimArray {}
```

Does this look like a valid bug?
Thanks

**Comment by dangodev** [comment]
Ah yup! This is a bug. Sorry for the delay. I’ll add a PR & a test to catch this right away. Sorry for the inconvenience!

**Comment by dangodev** [comment]
@scvnathan could you try the latest version? Using `npx` should pull the latest version now, or update to `1.3.1` if running locally.

**Comment by dangodev** [comment]
I even added a test for catching _nested_ nested arrays so we should be good 😛 

```yaml
environments:
  type: "array"
  items:
    type: "array"
    items:
      type: "array"
      items: { type: "string" }
```

should generate to:

```ts
environments?: string[][][];
```

**Comment by scvnathan** [comment]
Hey thanks @dangodev, nice job! I'll test this out again today
