### ISSUE TITLE
Breaks when there are spaces in models names

### ISSUE THREAD

**Issue by mmiszy** [manifoldco/swagger-to-ts#66]
My swagger.json is autogenerated and some of the models are "placeholder models" for irrelevant responses. By default, they contain spaces in their names i.e. `"Model 1"`, `"Model 2"` etc.
Unfortunately, currently this is not handled by `swagger-to-ts` and the following error is thrown:

```
'{' expected. (2:24)
  1 | declare namespace OpenAPI {
> 2 | export interface Model 99 {
```

Suggested solution would be to replace spaces with `_` or similar symbol.

**Comment by dangodev** [comment]
Ah good find @mmiszy! Could you give me a small snippet of your Swagger Schema with spaces so I can see it in context? Then I can push a fix.
