### ISSUE TITLE
Cannot re-export type definitions

### ISSUE THREAD

**Issue by FrozenKiwi** [manifoldco/swagger-to-ts#8]
I'm sure this is user-error, as I would think this is the most common use-case for this library.

I generate TS from spec, with output
    
     namespace MyLib {
        export interface ...
     }

Then compile & publish this as my own internal types definition to be included in other projects.  However, I can't re-import - when importing the file I see "file is not a module"

To fix I manually add in an "export " at the start of the file:

    export namespace MyLib { ... }

And this works.

Is this appropriate?  Is there a better way to resolve this?

**Comment by dangodev** [comment]
@FrozenKiwi out of curiosity, what version of TypeScript are you using? In my projects on 3.3.3333 I’m able to use `MyLib.interface` without any importing/exporting.

**Comment by dangodev** [comment]
I should add that I typically place my specs inside the `include` path in `tsconfig.json`. I wonder if that makes a difference, too.

Either way, there seems to be a helpful step missing in the README for sure.

**Comment by dangodev** [comment]
@FrozenKiwi thanks to another contributor with this problem, you can now export the namespace by passing `--export` to the CLI (refer to the README). Update to the new npm version `v1.1.3` to use this option. And let me know if this solves your problem!

**Comment by FrozenKiwi** [comment]
Oops - apologies for not replying: I had a bad filter on github for a while so missed all my notifications
