### ISSUE TITLE
Invalid character. SearchResult«Share»

### ISSUE THREAD

**Issue by elie222** [manifoldco/swagger-to-ts#86]
The `»` character is causing me problems with this package:

The error message looks like:

```
Invalid character. (65:30)

export interface SearchResult«Share» {
```

Seems like the Typescript doesn't like the `»` symbol.

**Comment by dangodev** [comment]
@elie222 yes TypeScript doesn’t allow `»`. How are you using it in Swagger? And why that character? We could possibly add support if I got a usage example of both your Swagger definition and the TypeScript code you’d like it to output.

**Comment by elie222** [comment]
Honestly I don’t know much about the code that generated it. I ended up replacing that character with underscores and then running it through the script. Thanks for the help

Best,
Eliezer

**Comment by dangodev** [comment]
OK. I’m going to close the issue then but if you ever run across another weird character, just provide a snippet of the Swagger definition, and what TypeScript code you’d like it to generate, and I’d be happy to re-open this issue.
